
#pragma once

#include <unordered_map>
#include <map>
#include <vector>
#include <string>

using namespace std;

namespace test {
  struct S {
    string key;
    string desc;
    string type;
  };
  const unordered_map<int, std::string> num_to_key = {
          {0,   "YB"},
          {1,   "CU"},
          {2,   "BW"},
          {3,   "VI"},
          {4,   "GX"},
          {5,   "LN"},
          {6,   "CA"},
          {7,   "ON"},
          {8,   "MS"},
          {9,   "OH"},
          {10,  "ZJ"},
          {11,  "QQ"},
          {12,  "ZA"},
          {13,  "UQ"},
          {14,  "AI"},
          {15,  "VM"},
          {16,  "YH"},
          {17,  "WX"},
          {18,  "MZ"},
          {19,  "ZF"},
          {20,  "JI"},
          {21,  "UB"},
          {22,  "XX"},
          {23,  "YA"},
          {24,  "FK"},
          {25,  "MQ"},
          {26,  "LH"},
          {27,  "RR"},
          {28,  "WB"},
          {29,  "XO"},
          {30,  "XJ"},
          {31,  "TG"},
          {32,  "EX"},
          {33,  "HT"},
          {34,  "DN"},
          {35,  "LX"},
          {36,  "AN"},
          {37,  "TZ"},
          {38,  "TB"},
          {39,  "YH"},
          {40,  "PI"},
          {41,  "QB"},
          {42,  "IW"},
          {43,  "CU"},
          {44,  "QC"},
          {45,  "FR"},
          {46,  "YP"},
          {47,  "ND"},
          {48,  "LJ"},
          {49,  "DO"},
          {50,  "NL"},
          {51,  "GG"},
          {52,  "DE"},
          {53,  "SZ"},
          {54,  "AL"},
          {55,  "ZN"},
          {56,  "WQ"},
          {57,  "VW"},
          {58,  "TO"},
          {59,  "AW"},
          {60,  "TB"},
          {61,  "ZY"},
          {62,  "QY"},
          {63,  "AU"},
          {64,  "MQ"},
          {65,  "NN"},
          {66,  "NI"},
          {67,  "OA"},
          {68,  "AF"},
          {69,  "MP"},
          {70,  "DW"},
          {71,  "NP"},
          {72,  "YW"},
          {73,  "RR"},
          {74,  "MD"},
          {75,  "CM"},
          {76,  "JB"},
          {77,  "NY"},
          {78,  "ZI"},
          {79,  "KM"},
          {80,  "XP"},
          {81,  "GX"},
          {82,  "OP"},
          {83,  "BB"},
          {84,  "AO"},
          {85,  "GY"},
          {86,  "VY"},
          {87,  "FL"},
          {88,  "IA"},
          {89,  "CE"},
          {90,  "GC"},
          {91,  "KK"},
          {92,  "WA"},
          {93,  "TL"},
          {94,  "HC"},
          {95,  "HK"},
          {96,  "XC"},
          {97,  "QL"},
          {98,  "UL"},
          {99,  "GT"},
          {100, "GM"},
          {101, "CL"},
          {102, "VY"},
          {103, "NW"},
          {104, "DN"},
          {105, "PJ"},
          {106, "WX"},
          {107, "HX"},
          {108, "KK"},
          {109, "GL"},
          {110, "XY"},
          {111, "GR"},
          {112, "FZ"},
          {113, "ZO"},
          {114, "NV"},
          {115, "XP"},
          {116, "WR"},
          {117, "YP"},
          {118, "SS"},
          {119, "PT"},
          {120, "DH"},
          {121, "RZ"},
          {122, "BA"},
          {123, "OY"},
          {124, "HF"},
          {125, "FW"},
          {126, "LG"},
          {127, "CM"},
          {128, "BN"},
          {129, "OC"},
          {130, "TG"},
          {131, "NT"},
          {132, "WQ"},
          {133, "TJ"},
          {134, "ST"},
          {135, "VK"},
          {136, "WV"},
          {137, "CU"},
          {138, "CT"},
          {139, "MF"},
          {140, "RA"},
          {141, "PJ"},
          {142, "FT"},
          {143, "RF"},
          {144, "KZ"},
          {145, "FQ"},
          {146, "SJ"},
          {147, "CK"},
          {148, "UC"},
          {149, "EC"},
          {150, "ET"},
          {151, "JC"},
          {152, "JM"},
          {153, "XD"},
          {154, "ZE"},
          {155, "PD"},
          {156, "EL"},
          {157, "JE"},
          {158, "VO"},
          {159, "JZ"},
          {160, "KL"},
          {161, "SR"},
          {162, "NK"},
          {163, "ZW"},
          {164, "XW"},
          {165, "NS"},
          {166, "LW"},
          {167, "AL"},
          {168, "QE"},
          {169, "QU"},
          {170, "FM"},
          {171, "CU"},
          {172, "EO"},
          {173, "NV"},
          {174, "SU"},
          {175, "SK"},
          {176, "FY"},
          {177, "NW"},
          {178, "PQ"},
          {179, "NB"},
          {180, "XD"},
          {181, "TB"},
          {182, "YJ"},
          {183, "FN"},
          {184, "AK"},
          {185, "ZU"},
          {186, "AB"},
          {187, "CY"},
          {188, "YA"},
          {189, "PV"},
          {190, "UT"},
          {191, "VE"},
          {192, "CV"},
          {193, "AZ"},
          {194, "HJ"},
          {195, "MV"},
          {196, "LW"},
          {197, "FX"},
          {198, "WD"},
          {199, "WX"},
  };
  const vector<std::pair<string, S>> vec = {
          {"YB", {"YB", "TWUMMSSIK98S",        "LIKE"}},
          {"CU", {"CU", "G0HZ7TIY5DGJ106YB",   "LIKE"}},
          {"BW", {"BW", "2MJDIKU1BI25RRTC2IS", "HOPELESS_CRACKERS"}},
          {"VI", {"VI", "QDGIZBQ25KV28C",      "IN_THE_WINTER"}},
          {"GX", {"GX", "19EOYLXIHMW5",        "SOMEONE"}},
          {"LN", {"LN", "5ZGZBC2GGL6JB",       "FEEL_OFF_A_CHICKEN"}},
          {"CA", {"CA", "A89RT9PBVB6PJN",      "HOPELESS_CRACKERS"}},
          {"ON", {"ON", "ZJATI7ZWN8CC6UROL8",  "IN_THE_WINTER"}},
          {"MS", {"MS", "S8KW3MZGM1UV",        "FEEL_OFF_A_CHICKEN"}},
          {"OH", {"OH", "YJOERGM0WI",          "LIKE"}},
          {"ZJ", {"ZJ", "1DU8FB5UJTJMOUH06TP", "IN_THE_WINTER"}},
          {"QQ", {"QQ", "080DXRCVXW63EJ2",     "HOPELESS_CRACKERS"}},
          {"ZA", {"ZA", "3RSI3R0ZX3S16I2",     "LIKE"}},
          {"UQ", {"UQ", "NQFQ0E3SW11",         "IN_THE_WINTER"}},
          {"AI", {"AI", "EBDZW94CUTGPFUZ",     "HELLO"}},
          {"VM", {"VM", "ZMEXENAO57F9IIT8",    "HELLO"}},
          {"YH", {"YH", "LDJMC9EJ5P2",         "FEEL_OFF_A_CHICKEN"}},
          {"WX", {"WX", "2UFSEZ83Y6BQI1AIW",   "HELLO"}},
          {"MZ", {"MZ", "MUQOLT5RS98IROKE",    "LIKE"}},
          {"ZF", {"ZF", "N482RYRPZEH5U4R0CEQ", "IN_THE_WINTER"}},
          {"JI", {"JI", "7BM5VP4GM97RHJ5X",    "LIKE"}},
          {"UB", {"UB", "0YPDR53GGRKU0I",      "SMELLS"}},
          {"XX", {"XX", "B7K4EQW9223",         "SMELLS"}},
          {"YA", {"YA", "YLVAZDJ4HJPN97V5",    "HOPELESS_CRACKERS"}},
          {"FK", {"FK", "KG0HD69WHK",          "FEEL_OFF_A_CHICKEN"}},
          {"MQ", {"MQ", "0W2HWO1VBTDBU23ID",   "LIKE"}},
          {"LH", {"LH", "ENZMT6X6FAPIW",       "LIKE"}},
          {"RR", {"RR", "DU4NS1TLRXO3IFGRW",   "LIKE"}},
          {"WB", {"WB", "AQ0L6EE4TI",          "SMELLS"}},
          {"XO", {"XO", "A1382HGT8ZEEYJQN",    "FEEL_OFF_A_CHICKEN"}},
          {"XJ", {"XJ", "2D90ABW8Q4PCICGF",    "SOMEONE"}},
          {"TG", {"TG", "J5SFHK6Q217CJG0",     "HOPELESS_CRACKERS"}},
          {"EX", {"EX", "Q869VVLFQFU0M",       "HOPELESS_CRACKERS"}},
          {"HT", {"HT", "EAD1R1QTLG0PVJD5",    "LIKE"}},
          {"DN", {"DN", "Y4M2TC3DCJ2NB0FM92",  "LIKE"}},
          {"LX", {"LX", "J67BRR6H34H1A0",      "LIKE"}},
          {"AN", {"AN", "QCHNB1DHLQ9T1EOG",    "HELLO"}},
          {"TZ", {"TZ", "FC4FHKY106KK1EZM",    "SOMEONE"}},
          {"TB", {"TB", "ID6KBJ1Y0R00W",       "HOPELESS_CRACKERS"}},
          {"YH", {"YH", "Q9VGO88DZGA4BIP",     "HOPELESS_CRACKERS"}},
          {"PI", {"PI", "I8UOLS13FBNCXA",      "HOPELESS_CRACKERS"}},
          {"QB", {"QB", "JW9OY2MJHD7BJPU6HJC", "HELLO"}},
          {"IW", {"IW", "VXJTNPPCW2MBQMX0",    "LIKE"}},
          {"CU", {"CU", "H1HZRGA7PSTVDJ",      "HOPELESS_CRACKERS"}},
          {"QC", {"QC", "2LGJ0K6OHK1F86IMGY",  "IN_THE_WINTER"}},
          {"FR", {"FR", "BPN87VZ54F1K",        "HOPELESS_CRACKERS"}},
          {"YP", {"YP", "ZUZ7DDG3ECDHP",       "SOMEONE"}},
          {"ND", {"ND", "SCCHQ0LYKVW34J",      "LIKE"}},
          {"LJ", {"LJ", "93NJ8AA8KLWAG8834BT", "SMELLS"}},
          {"DO", {"DO", "SXZUPYLT74T52IM4MYE", "LIKE"}},
          {"NL", {"NL", "DXAF33QQ1AXGSSZ6",    "SMELLS"}},
          {"GG", {"GG", "TX6EIQMJNX",          "SOMEONE"}},
          {"DE", {"DE", "F1T4JL7M29I",         "IN_THE_WINTER"}},
          {"SZ", {"SZ", "THBO1PN8TBLV0FZNSW9", "IN_THE_WINTER"}},
          {"AL", {"AL", "IX6F2DYLAAP2Y9ZXQ",   "FEEL_OFF_A_CHICKEN"}},
          {"ZN", {"ZN", "ZIFTA6B3XQWW",        "HOPELESS_CRACKERS"}},
          {"WQ", {"WQ", "Q78U79NB04JXKVK",     "SOMEONE"}},
          {"VW", {"VW", "LJ321PQROE8O",        "FEEL_OFF_A_CHICKEN"}},
          {"TO", {"TO", "07ZYH6BOVGSQ0BBMHIG", "LIKE"}},
          {"AW", {"AW", "VF44D4O9LSSMF5HN",    "SOMEONE"}},
          {"TB", {"TB", "H24P4I344W",          "SOMEONE"}},
          {"ZY", {"ZY", "9IQY9ERAPFOP",        "HOPELESS_CRACKERS"}},
          {"QY", {"QY", "V9JDET0XINLD2CUUYV",  "SOMEONE"}},
          {"AU", {"AU", "LPWLHPWCLGYW9RS5",    "IN_THE_WINTER"}},
          {"MQ", {"MQ", "6T9OKKO1TI0TTGHROM",  "HOPELESS_CRACKERS"}},
          {"NN", {"NN", "48E5YQE8WPSI3",       "HELLO"}},
          {"NI", {"NI", "ZJ56R71104XAF81EPAH", "IN_THE_WINTER"}},
          {"OA", {"OA", "U2HAT05IAUMHWGZ3",    "FEEL_OFF_A_CHICKEN"}},
          {"AF", {"AF", "KGNKX4DR5RL5AZ",      "IN_THE_WINTER"}},
          {"MP", {"MP", "M7JS5G299Y8X1RL8",    "HELLO"}},
          {"DW", {"DW", "VZA5VE6Y5YC7IS350G",  "FEEL_OFF_A_CHICKEN"}},
          {"NP", {"NP", "Y8S5XZWB6I6HXNXT",    "HOPELESS_CRACKERS"}},
          {"YW", {"YW", "U3VX19YXLMMOOKIK",    "FEEL_OFF_A_CHICKEN"}},
          {"RR", {"RR", "1BZUFCL71NV",         "HOPELESS_CRACKERS"}},
          {"MD", {"MD", "7KPVAAFWWU7O",        "SMELLS"}},
          {"CM", {"CM", "4GECQQCENHYU",        "IN_THE_WINTER"}},
          {"JB", {"JB", "S2FXVC1M5BZ17A",      "SMELLS"}},
          {"NY", {"NY", "Y0HBHKYYARCANW1TZ0U", "SOMEONE"}},
          {"ZI", {"ZI", "QB4U9OW32IXJ0",       "HOPELESS_CRACKERS"}},
          {"KM", {"KM", "2FKP3758AOO49OJALY",  "HOPELESS_CRACKERS"}},
          {"XP", {"XP", "B6RNNS85L29UOH",      "HOPELESS_CRACKERS"}},
          {"GX", {"GX", "2WLO809JI4BZBYOEC",   "SMELLS"}},
          {"OP", {"OP", "QDYZCGAPPDKD4TWL0Y",  "LIKE"}},
          {"BB", {"BB", "V2VORZHWCRYE7LMP",    "HELLO"}},
          {"AO", {"AO", "7FZIH6XHT3S9MQ",      "FEEL_OFF_A_CHICKEN"}},
          {"GY", {"GY", "IZ5K4GWNP8JC",        "IN_THE_WINTER"}},
          {"VY", {"VY", "V4AVU090QDYJ0F79",    "SMELLS"}},
          {"FL", {"FL", "VB7Z28LFJFIHP4J",     "SOMEONE"}},
          {"IA", {"IA", "CKUZ2TQRM779VB",      "LIKE"}},
          {"CE", {"CE", "HIUWJES5B7",          "HELLO"}},
          {"GC", {"GC", "PFQ3LNKWE07WB3QS8O",  "LIKE"}},
          {"KK", {"KK", "76KQ8H63M5",          "FEEL_OFF_A_CHICKEN"}},
          {"WA", {"WA", "BJZNCUYM5HLAOJ6U6",   "SMELLS"}},
          {"TL", {"TL", "IPU6KBCA00WQ",        "HELLO"}},
          {"HC", {"HC", "QKBJYAH0Q0XK9W",      "HELLO"}},
          {"HK", {"HK", "NMFQ56BJUJYZ4CN",     "HELLO"}},
          {"XC", {"XC", "WU4TB9QEKG9C1Y4YQW",  "SOMEONE"}},
          {"QL", {"QL", "7VZCRK61OYPPZJWCJRM", "LIKE"}},
          {"UL", {"UL", "KOIVI5BVHBTXIAXRG7",  "IN_THE_WINTER"}},
          {"GT", {"GT", "4V21YORTXLKV3Q",      "FEEL_OFF_A_CHICKEN"}},
          {"GM", {"GM", "QP3UFM1K5JZ9BYNR",    "FEEL_OFF_A_CHICKEN"}},
          {"CL", {"CL", "HU9K0VKGV8IPU",       "HOPELESS_CRACKERS"}},
          {"VY", {"VY", "3J4B4QLAHJ9XHDOGGYK", "FEEL_OFF_A_CHICKEN"}},
          {"NW", {"NW", "DUVCN5EK89O",         "HELLO"}},
          {"DN", {"DN", "X8WPJZ1H2KN",         "HELLO"}},
          {"PJ", {"PJ", "D6GEGBS7HH4",         "FEEL_OFF_A_CHICKEN"}},
          {"WX", {"WX", "VRIF43J7QAXFQWV",     "SOMEONE"}},
          {"HX", {"HX", "L6SDEWAST00LYO",      "SMELLS"}},
          {"KK", {"KK", "R1TQ8LAZX9",          "HELLO"}},
          {"GL", {"GL", "BH86WGTSIMRBAL0PBZ",  "HOPELESS_CRACKERS"}},
          {"XY", {"XY", "TFBJNGLR4NPSL33",     "HOPELESS_CRACKERS"}},
          {"GR", {"GR", "HXAKBVVMNVLXOVQ",     "IN_THE_WINTER"}},
          {"FZ", {"FZ", "2WPH37M7VQZQ63C7C4",  "LIKE"}},
          {"ZO", {"ZO", "7TZ4I7H9AFZXF9ACH",   "SMELLS"}},
          {"NV", {"NV", "A37TB97IO12",         "IN_THE_WINTER"}},
          {"XP", {"XP", "FXKI6BARPB3QE9T",     "SMELLS"}},
          {"WR", {"WR", "FW8MCLUTS8PEI7LXE6",  "FEEL_OFF_A_CHICKEN"}},
          {"YP", {"YP", "Z6H0KS1IS1822",       "SMELLS"}},
          {"SS", {"SS", "8FPSRCV9TWP3J2U",     "HOPELESS_CRACKERS"}},
          {"PT", {"PT", "QFWD3MXBF7WO7R24",    "SOMEONE"}},
          {"DH", {"DH", "7FHW2ZL7VOW",         "HOPELESS_CRACKERS"}},
          {"RZ", {"RZ", "9PFTL6WAJDJLA9N7HQ4", "IN_THE_WINTER"}},
          {"BA", {"BA", "DO8I2NEDZN9N03E4C",   "HOPELESS_CRACKERS"}},
          {"OY", {"OY", "5368VJP7CE4OGGX3D",   "FEEL_OFF_A_CHICKEN"}},
          {"HF", {"HF", "MVRFZ3MVUTHZOW",      "HOPELESS_CRACKERS"}},
          {"FW", {"FW", "OZ6FBPXYGASA",        "FEEL_OFF_A_CHICKEN"}},
          {"LG", {"LG", "PGL5UF021VH9PPKQZA",  "HELLO"}},
          {"CM", {"CM", "RUL8OTJH6103OIKGKH",  "SMELLS"}},
          {"BN", {"BN", "0GCVB45TWI6UJ",       "LIKE"}},
          {"OC", {"OC", "GDO8O7UGQJO",         "SOMEONE"}},
          {"TG", {"TG", "LKK2J89NA201CQJD",    "HOPELESS_CRACKERS"}},
          {"NT", {"NT", "U8L5U5Q9PZMRI73KO",   "FEEL_OFF_A_CHICKEN"}},
          {"WQ", {"WQ", "PH2MZ3CKGSB03KG4M8",  "IN_THE_WINTER"}},
          {"TJ", {"TJ", "KSS51VUPSPMN",        "SOMEONE"}},
          {"ST", {"ST", "5IY9Y3C06ZCOY7",      "HELLO"}},
          {"VK", {"VK", "F9OVU74QHIWR1VAEC6N", "HOPELESS_CRACKERS"}},
          {"WV", {"WV", "6TC9A3DADUIWF5XN5",   "IN_THE_WINTER"}},
          {"CU", {"CU", "EPYXH6O91CHOS31",     "SMELLS"}},
          {"CT", {"CT", "MU7H6L1M3K32F999M71", "SMELLS"}},
          {"MF", {"MF", "2Q9N4FKTHIW5GX3",     "SOMEONE"}},
          {"RA", {"RA", "E0VGIBFYSYCOZ36QLUG", "SMELLS"}},
          {"PJ", {"PJ", "2WFPCRPP0WF4",        "FEEL_OFF_A_CHICKEN"}},
          {"FT", {"FT", "ST2FTJ6JMF6KCS4X13",  "FEEL_OFF_A_CHICKEN"}},
          {"RF", {"RF", "W3RI6VBQ8RXF",        "SOMEONE"}},
          {"KZ", {"KZ", "AKPAB40YHJ65I6",      "IN_THE_WINTER"}},
          {"FQ", {"FQ", "Z6M9IW0DM7SBNVD9",    "IN_THE_WINTER"}},
          {"SJ", {"SJ", "Z2WSU1L8KQ0QFI",      "SMELLS"}},
          {"CK", {"CK", "PUNCNZRIXE29",        "SMELLS"}},
          {"UC", {"UC", "CKH988MZ3IWX",        "SMELLS"}},
          {"EC", {"EC", "P09Y5UFO0H",          "LIKE"}},
          {"ET", {"ET", "NH7O72SPB1HF",        "HELLO"}},
          {"JC", {"JC", "9U7WEHPFPPA9",        "HOPELESS_CRACKERS"}},
          {"JM", {"JM", "VSILHOQUIJW1HS0P95",  "LIKE"}},
          {"XD", {"XD", "1ANVL7B7IX6TGLO7",    "HOPELESS_CRACKERS"}},
          {"ZE", {"ZE", "IF9NAS18LB1",         "FEEL_OFF_A_CHICKEN"}},
          {"PD", {"PD", "UP3Q9IZPJGIP4OS",     "IN_THE_WINTER"}},
          {"EL", {"EL", "QNMFJSX3Z3Y720H5O",   "SMELLS"}},
          {"JE", {"JE", "NS47OK21ZV",          "LIKE"}},
          {"VO", {"VO", "D4EDQ7X4ED3EVQ9HR5",  "IN_THE_WINTER"}},
          {"JZ", {"JZ", "YDMQR24B1XGIO8R",     "SMELLS"}},
          {"KL", {"KL", "LJJ48C79I2D",         "SMELLS"}},
          {"SR", {"SR", "OQE18CPT8BD2HNN1O",   "HELLO"}},
          {"NK", {"NK", "T9TVRUSVROTV",        "LIKE"}},
          {"ZW", {"ZW", "BVWASIHIT5",          "LIKE"}},
          {"XW", {"XW", "VBIUSKIVC4O",         "HOPELESS_CRACKERS"}},
          {"NS", {"NS", "CV5GT6H917ZQ5",       "FEEL_OFF_A_CHICKEN"}},
          {"LW", {"LW", "P1E5J06CG1ED94LS21",  "SMELLS"}},
          {"AL", {"AL", "URS12EB7UDR7A",       "HOPELESS_CRACKERS"}},
          {"QE", {"QE", "BCU2B7IKJRW1TKPEE2",  "SMELLS"}},
          {"QU", {"QU", "ZFKFL58F19",          "HOPELESS_CRACKERS"}},
          {"FM", {"FM", "PKU88B0SR97NWM9SE",   "SMELLS"}},
          {"CU", {"CU", "OSL70SNRCNA",         "HOPELESS_CRACKERS"}},
          {"EO", {"EO", "2ZZ94JOSKN7WP7",      "LIKE"}},
          {"NV", {"NV", "QT4EZ76M7E0",         "FEEL_OFF_A_CHICKEN"}},
          {"SU", {"SU", "G6ZGLDM4QC",          "FEEL_OFF_A_CHICKEN"}},
          {"SK", {"SK", "FOHNFES9Z87V",        "SOMEONE"}},
          {"FY", {"FY", "8TMHKPZKMKK",         "LIKE"}},
          {"NW", {"NW", "V929M5X6GHZORLOZZ8",  "FEEL_OFF_A_CHICKEN"}},
          {"PQ", {"PQ", "4M4H80CTFNCSDDSS",    "SOMEONE"}},
          {"NB", {"NB", "A7JYJ4TBSAK",         "FEEL_OFF_A_CHICKEN"}},
          {"XD", {"XD", "262GYDR741VADAMB74",  "LIKE"}},
          {"TB", {"TB", "RXWCYZ39ILATWH5B2",   "FEEL_OFF_A_CHICKEN"}},
          {"YJ", {"YJ", "9QSS2UNOW8",          "FEEL_OFF_A_CHICKEN"}},
          {"FN", {"FN", "RLMN5L3UVVVAFT42G",   "HELLO"}},
          {"AK", {"AK", "F3BLVX2M5DYPSD6N",    "IN_THE_WINTER"}},
          {"ZU", {"ZU", "R0YOPL1BCJJJH5VE3T0", "LIKE"}},
          {"AB", {"AB", "ZDWMVVOFSRWBY49A",    "LIKE"}},
          {"CY", {"CY", "5LW6OAYPUSG3LE6D61L", "IN_THE_WINTER"}},
          {"YA", {"YA", "4I47LIY0EUZ",         "LIKE"}},
          {"PV", {"PV", "ZWZFCGCLS4TD4C",      "IN_THE_WINTER"}},
          {"UT", {"UT", "E039WXQP3TU9HQ",      "SMELLS"}},
          {"VE", {"VE", "0TP7D8K60GD3H9DJBGO", "HELLO"}},
          {"CV", {"CV", "BQ28NJQ5DHQ12M23",    "SOMEONE"}},
          {"AZ", {"AZ", "JE61S0T0O93R6",       "FEEL_OFF_A_CHICKEN"}},
          {"HJ", {"HJ", "AP42QNCM7N0KC",       "SMELLS"}},
          {"MV", {"MV", "7SMM5KEQ1X",          "IN_THE_WINTER"}},
          {"LW", {"LW", "6PLJ660LFSWW9G2",     "SMELLS"}},
          {"FX", {"FX", "TP5RPLY4XEP0G58XI",   "LIKE"}},
          {"WD", {"WD", "7XAEHVJS1YRDG5I",     "FEEL_OFF_A_CHICKEN"}},
          {"WX", {"WX", "3MJME3FCSFHY",        "IN_THE_WINTER"}},
  };
  const unordered_map<string, S> u_mp = {
          {"YB", {"YB", "TWUMMSSIK98S",        "LIKE"}},
          {"CU", {"CU", "G0HZ7TIY5DGJ106YB",   "LIKE"}},
          {"BW", {"BW", "2MJDIKU1BI25RRTC2IS", "HOPELESS_CRACKERS"}},
          {"VI", {"VI", "QDGIZBQ25KV28C",      "IN_THE_WINTER"}},
          {"GX", {"GX", "19EOYLXIHMW5",        "SOMEONE"}},
          {"LN", {"LN", "5ZGZBC2GGL6JB",       "FEEL_OFF_A_CHICKEN"}},
          {"CA", {"CA", "A89RT9PBVB6PJN",      "HOPELESS_CRACKERS"}},
          {"ON", {"ON", "ZJATI7ZWN8CC6UROL8",  "IN_THE_WINTER"}},
          {"MS", {"MS", "S8KW3MZGM1UV",        "FEEL_OFF_A_CHICKEN"}},
          {"OH", {"OH", "YJOERGM0WI",          "LIKE"}},
          {"ZJ", {"ZJ", "1DU8FB5UJTJMOUH06TP", "IN_THE_WINTER"}},
          {"QQ", {"QQ", "080DXRCVXW63EJ2",     "HOPELESS_CRACKERS"}},
          {"ZA", {"ZA", "3RSI3R0ZX3S16I2",     "LIKE"}},
          {"UQ", {"UQ", "NQFQ0E3SW11",         "IN_THE_WINTER"}},
          {"AI", {"AI", "EBDZW94CUTGPFUZ",     "HELLO"}},
          {"VM", {"VM", "ZMEXENAO57F9IIT8",    "HELLO"}},
          {"YH", {"YH", "LDJMC9EJ5P2",         "FEEL_OFF_A_CHICKEN"}},
          {"WX", {"WX", "2UFSEZ83Y6BQI1AIW",   "HELLO"}},
          {"MZ", {"MZ", "MUQOLT5RS98IROKE",    "LIKE"}},
          {"ZF", {"ZF", "N482RYRPZEH5U4R0CEQ", "IN_THE_WINTER"}},
          {"JI", {"JI", "7BM5VP4GM97RHJ5X",    "LIKE"}},
          {"UB", {"UB", "0YPDR53GGRKU0I",      "SMELLS"}},
          {"XX", {"XX", "B7K4EQW9223",         "SMELLS"}},
          {"YA", {"YA", "YLVAZDJ4HJPN97V5",    "HOPELESS_CRACKERS"}},
          {"FK", {"FK", "KG0HD69WHK",          "FEEL_OFF_A_CHICKEN"}},
          {"MQ", {"MQ", "0W2HWO1VBTDBU23ID",   "LIKE"}},
          {"LH", {"LH", "ENZMT6X6FAPIW",       "LIKE"}},
          {"RR", {"RR", "DU4NS1TLRXO3IFGRW",   "LIKE"}},
          {"WB", {"WB", "AQ0L6EE4TI",          "SMELLS"}},
          {"XO", {"XO", "A1382HGT8ZEEYJQN",    "FEEL_OFF_A_CHICKEN"}},
          {"XJ", {"XJ", "2D90ABW8Q4PCICGF",    "SOMEONE"}},
          {"TG", {"TG", "J5SFHK6Q217CJG0",     "HOPELESS_CRACKERS"}},
          {"EX", {"EX", "Q869VVLFQFU0M",       "HOPELESS_CRACKERS"}},
          {"HT", {"HT", "EAD1R1QTLG0PVJD5",    "LIKE"}},
          {"DN", {"DN", "Y4M2TC3DCJ2NB0FM92",  "LIKE"}},
          {"LX", {"LX", "J67BRR6H34H1A0",      "LIKE"}},
          {"AN", {"AN", "QCHNB1DHLQ9T1EOG",    "HELLO"}},
          {"TZ", {"TZ", "FC4FHKY106KK1EZM",    "SOMEONE"}},
          {"TB", {"TB", "ID6KBJ1Y0R00W",       "HOPELESS_CRACKERS"}},
          {"YH", {"YH", "Q9VGO88DZGA4BIP",     "HOPELESS_CRACKERS"}},
          {"PI", {"PI", "I8UOLS13FBNCXA",      "HOPELESS_CRACKERS"}},
          {"QB", {"QB", "JW9OY2MJHD7BJPU6HJC", "HELLO"}},
          {"IW", {"IW", "VXJTNPPCW2MBQMX0",    "LIKE"}},
          {"CU", {"CU", "H1HZRGA7PSTVDJ",      "HOPELESS_CRACKERS"}},
          {"QC", {"QC", "2LGJ0K6OHK1F86IMGY",  "IN_THE_WINTER"}},
          {"FR", {"FR", "BPN87VZ54F1K",        "HOPELESS_CRACKERS"}},
          {"YP", {"YP", "ZUZ7DDG3ECDHP",       "SOMEONE"}},
          {"ND", {"ND", "SCCHQ0LYKVW34J",      "LIKE"}},
          {"LJ", {"LJ", "93NJ8AA8KLWAG8834BT", "SMELLS"}},
          {"DO", {"DO", "SXZUPYLT74T52IM4MYE", "LIKE"}},
          {"NL", {"NL", "DXAF33QQ1AXGSSZ6",    "SMELLS"}},
          {"GG", {"GG", "TX6EIQMJNX",          "SOMEONE"}},
          {"DE", {"DE", "F1T4JL7M29I",         "IN_THE_WINTER"}},
          {"SZ", {"SZ", "THBO1PN8TBLV0FZNSW9", "IN_THE_WINTER"}},
          {"AL", {"AL", "IX6F2DYLAAP2Y9ZXQ",   "FEEL_OFF_A_CHICKEN"}},
          {"ZN", {"ZN", "ZIFTA6B3XQWW",        "HOPELESS_CRACKERS"}},
          {"WQ", {"WQ", "Q78U79NB04JXKVK",     "SOMEONE"}},
          {"VW", {"VW", "LJ321PQROE8O",        "FEEL_OFF_A_CHICKEN"}},
          {"TO", {"TO", "07ZYH6BOVGSQ0BBMHIG", "LIKE"}},
          {"AW", {"AW", "VF44D4O9LSSMF5HN",    "SOMEONE"}},
          {"TB", {"TB", "H24P4I344W",          "SOMEONE"}},
          {"ZY", {"ZY", "9IQY9ERAPFOP",        "HOPELESS_CRACKERS"}},
          {"QY", {"QY", "V9JDET0XINLD2CUUYV",  "SOMEONE"}},
          {"AU", {"AU", "LPWLHPWCLGYW9RS5",    "IN_THE_WINTER"}},
          {"MQ", {"MQ", "6T9OKKO1TI0TTGHROM",  "HOPELESS_CRACKERS"}},
          {"NN", {"NN", "48E5YQE8WPSI3",       "HELLO"}},
          {"NI", {"NI", "ZJ56R71104XAF81EPAH", "IN_THE_WINTER"}},
          {"OA", {"OA", "U2HAT05IAUMHWGZ3",    "FEEL_OFF_A_CHICKEN"}},
          {"AF", {"AF", "KGNKX4DR5RL5AZ",      "IN_THE_WINTER"}},
          {"MP", {"MP", "M7JS5G299Y8X1RL8",    "HELLO"}},
          {"DW", {"DW", "VZA5VE6Y5YC7IS350G",  "FEEL_OFF_A_CHICKEN"}},
          {"NP", {"NP", "Y8S5XZWB6I6HXNXT",    "HOPELESS_CRACKERS"}},
          {"YW", {"YW", "U3VX19YXLMMOOKIK",    "FEEL_OFF_A_CHICKEN"}},
          {"RR", {"RR", "1BZUFCL71NV",         "HOPELESS_CRACKERS"}},
          {"MD", {"MD", "7KPVAAFWWU7O",        "SMELLS"}},
          {"CM", {"CM", "4GECQQCENHYU",        "IN_THE_WINTER"}},
          {"JB", {"JB", "S2FXVC1M5BZ17A",      "SMELLS"}},
          {"NY", {"NY", "Y0HBHKYYARCANW1TZ0U", "SOMEONE"}},
          {"ZI", {"ZI", "QB4U9OW32IXJ0",       "HOPELESS_CRACKERS"}},
          {"KM", {"KM", "2FKP3758AOO49OJALY",  "HOPELESS_CRACKERS"}},
          {"XP", {"XP", "B6RNNS85L29UOH",      "HOPELESS_CRACKERS"}},
          {"GX", {"GX", "2WLO809JI4BZBYOEC",   "SMELLS"}},
          {"OP", {"OP", "QDYZCGAPPDKD4TWL0Y",  "LIKE"}},
          {"BB", {"BB", "V2VORZHWCRYE7LMP",    "HELLO"}},
          {"AO", {"AO", "7FZIH6XHT3S9MQ",      "FEEL_OFF_A_CHICKEN"}},
          {"GY", {"GY", "IZ5K4GWNP8JC",        "IN_THE_WINTER"}},
          {"VY", {"VY", "V4AVU090QDYJ0F79",    "SMELLS"}},
          {"FL", {"FL", "VB7Z28LFJFIHP4J",     "SOMEONE"}},
          {"IA", {"IA", "CKUZ2TQRM779VB",      "LIKE"}},
          {"CE", {"CE", "HIUWJES5B7",          "HELLO"}},
          {"GC", {"GC", "PFQ3LNKWE07WB3QS8O",  "LIKE"}},
          {"KK", {"KK", "76KQ8H63M5",          "FEEL_OFF_A_CHICKEN"}},
          {"WA", {"WA", "BJZNCUYM5HLAOJ6U6",   "SMELLS"}},
          {"TL", {"TL", "IPU6KBCA00WQ",        "HELLO"}},
          {"HC", {"HC", "QKBJYAH0Q0XK9W",      "HELLO"}},
          {"HK", {"HK", "NMFQ56BJUJYZ4CN",     "HELLO"}},
          {"XC", {"XC", "WU4TB9QEKG9C1Y4YQW",  "SOMEONE"}},
          {"QL", {"QL", "7VZCRK61OYPPZJWCJRM", "LIKE"}},
          {"UL", {"UL", "KOIVI5BVHBTXIAXRG7",  "IN_THE_WINTER"}},
          {"GT", {"GT", "4V21YORTXLKV3Q",      "FEEL_OFF_A_CHICKEN"}},
          {"GM", {"GM", "QP3UFM1K5JZ9BYNR",    "FEEL_OFF_A_CHICKEN"}},
          {"CL", {"CL", "HU9K0VKGV8IPU",       "HOPELESS_CRACKERS"}},
          {"VY", {"VY", "3J4B4QLAHJ9XHDOGGYK", "FEEL_OFF_A_CHICKEN"}},
          {"NW", {"NW", "DUVCN5EK89O",         "HELLO"}},
          {"DN", {"DN", "X8WPJZ1H2KN",         "HELLO"}},
          {"PJ", {"PJ", "D6GEGBS7HH4",         "FEEL_OFF_A_CHICKEN"}},
          {"WX", {"WX", "VRIF43J7QAXFQWV",     "SOMEONE"}},
          {"HX", {"HX", "L6SDEWAST00LYO",      "SMELLS"}},
          {"KK", {"KK", "R1TQ8LAZX9",          "HELLO"}},
          {"GL", {"GL", "BH86WGTSIMRBAL0PBZ",  "HOPELESS_CRACKERS"}},
          {"XY", {"XY", "TFBJNGLR4NPSL33",     "HOPELESS_CRACKERS"}},
          {"GR", {"GR", "HXAKBVVMNVLXOVQ",     "IN_THE_WINTER"}},
          {"FZ", {"FZ", "2WPH37M7VQZQ63C7C4",  "LIKE"}},
          {"ZO", {"ZO", "7TZ4I7H9AFZXF9ACH",   "SMELLS"}},
          {"NV", {"NV", "A37TB97IO12",         "IN_THE_WINTER"}},
          {"XP", {"XP", "FXKI6BARPB3QE9T",     "SMELLS"}},
          {"WR", {"WR", "FW8MCLUTS8PEI7LXE6",  "FEEL_OFF_A_CHICKEN"}},
          {"YP", {"YP", "Z6H0KS1IS1822",       "SMELLS"}},
          {"SS", {"SS", "8FPSRCV9TWP3J2U",     "HOPELESS_CRACKERS"}},
          {"PT", {"PT", "QFWD3MXBF7WO7R24",    "SOMEONE"}},
          {"DH", {"DH", "7FHW2ZL7VOW",         "HOPELESS_CRACKERS"}},
          {"RZ", {"RZ", "9PFTL6WAJDJLA9N7HQ4", "IN_THE_WINTER"}},
          {"BA", {"BA", "DO8I2NEDZN9N03E4C",   "HOPELESS_CRACKERS"}},
          {"OY", {"OY", "5368VJP7CE4OGGX3D",   "FEEL_OFF_A_CHICKEN"}},
          {"HF", {"HF", "MVRFZ3MVUTHZOW",      "HOPELESS_CRACKERS"}},
          {"FW", {"FW", "OZ6FBPXYGASA",        "FEEL_OFF_A_CHICKEN"}},
          {"LG", {"LG", "PGL5UF021VH9PPKQZA",  "HELLO"}},
          {"CM", {"CM", "RUL8OTJH6103OIKGKH",  "SMELLS"}},
          {"BN", {"BN", "0GCVB45TWI6UJ",       "LIKE"}},
          {"OC", {"OC", "GDO8O7UGQJO",         "SOMEONE"}},
          {"TG", {"TG", "LKK2J89NA201CQJD",    "HOPELESS_CRACKERS"}},
          {"NT", {"NT", "U8L5U5Q9PZMRI73KO",   "FEEL_OFF_A_CHICKEN"}},
          {"WQ", {"WQ", "PH2MZ3CKGSB03KG4M8",  "IN_THE_WINTER"}},
          {"TJ", {"TJ", "KSS51VUPSPMN",        "SOMEONE"}},
          {"ST", {"ST", "5IY9Y3C06ZCOY7",      "HELLO"}},
          {"VK", {"VK", "F9OVU74QHIWR1VAEC6N", "HOPELESS_CRACKERS"}},
          {"WV", {"WV", "6TC9A3DADUIWF5XN5",   "IN_THE_WINTER"}},
          {"CU", {"CU", "EPYXH6O91CHOS31",     "SMELLS"}},
          {"CT", {"CT", "MU7H6L1M3K32F999M71", "SMELLS"}},
          {"MF", {"MF", "2Q9N4FKTHIW5GX3",     "SOMEONE"}},
          {"RA", {"RA", "E0VGIBFYSYCOZ36QLUG", "SMELLS"}},
          {"PJ", {"PJ", "2WFPCRPP0WF4",        "FEEL_OFF_A_CHICKEN"}},
          {"FT", {"FT", "ST2FTJ6JMF6KCS4X13",  "FEEL_OFF_A_CHICKEN"}},
          {"RF", {"RF", "W3RI6VBQ8RXF",        "SOMEONE"}},
          {"KZ", {"KZ", "AKPAB40YHJ65I6",      "IN_THE_WINTER"}},
          {"FQ", {"FQ", "Z6M9IW0DM7SBNVD9",    "IN_THE_WINTER"}},
          {"SJ", {"SJ", "Z2WSU1L8KQ0QFI",      "SMELLS"}},
          {"CK", {"CK", "PUNCNZRIXE29",        "SMELLS"}},
          {"UC", {"UC", "CKH988MZ3IWX",        "SMELLS"}},
          {"EC", {"EC", "P09Y5UFO0H",          "LIKE"}},
          {"ET", {"ET", "NH7O72SPB1HF",        "HELLO"}},
          {"JC", {"JC", "9U7WEHPFPPA9",        "HOPELESS_CRACKERS"}},
          {"JM", {"JM", "VSILHOQUIJW1HS0P95",  "LIKE"}},
          {"XD", {"XD", "1ANVL7B7IX6TGLO7",    "HOPELESS_CRACKERS"}},
          {"ZE", {"ZE", "IF9NAS18LB1",         "FEEL_OFF_A_CHICKEN"}},
          {"PD", {"PD", "UP3Q9IZPJGIP4OS",     "IN_THE_WINTER"}},
          {"EL", {"EL", "QNMFJSX3Z3Y720H5O",   "SMELLS"}},
          {"JE", {"JE", "NS47OK21ZV",          "LIKE"}},
          {"VO", {"VO", "D4EDQ7X4ED3EVQ9HR5",  "IN_THE_WINTER"}},
          {"JZ", {"JZ", "YDMQR24B1XGIO8R",     "SMELLS"}},
          {"KL", {"KL", "LJJ48C79I2D",         "SMELLS"}},
          {"SR", {"SR", "OQE18CPT8BD2HNN1O",   "HELLO"}},
          {"NK", {"NK", "T9TVRUSVROTV",        "LIKE"}},
          {"ZW", {"ZW", "BVWASIHIT5",          "LIKE"}},
          {"XW", {"XW", "VBIUSKIVC4O",         "HOPELESS_CRACKERS"}},
          {"NS", {"NS", "CV5GT6H917ZQ5",       "FEEL_OFF_A_CHICKEN"}},
          {"LW", {"LW", "P1E5J06CG1ED94LS21",  "SMELLS"}},
          {"AL", {"AL", "URS12EB7UDR7A",       "HOPELESS_CRACKERS"}},
          {"QE", {"QE", "BCU2B7IKJRW1TKPEE2",  "SMELLS"}},
          {"QU", {"QU", "ZFKFL58F19",          "HOPELESS_CRACKERS"}},
          {"FM", {"FM", "PKU88B0SR97NWM9SE",   "SMELLS"}},
          {"CU", {"CU", "OSL70SNRCNA",         "HOPELESS_CRACKERS"}},
          {"EO", {"EO", "2ZZ94JOSKN7WP7",      "LIKE"}},
          {"NV", {"NV", "QT4EZ76M7E0",         "FEEL_OFF_A_CHICKEN"}},
          {"SU", {"SU", "G6ZGLDM4QC",          "FEEL_OFF_A_CHICKEN"}},
          {"SK", {"SK", "FOHNFES9Z87V",        "SOMEONE"}},
          {"FY", {"FY", "8TMHKPZKMKK",         "LIKE"}},
          {"NW", {"NW", "V929M5X6GHZORLOZZ8",  "FEEL_OFF_A_CHICKEN"}},
          {"PQ", {"PQ", "4M4H80CTFNCSDDSS",    "SOMEONE"}},
          {"NB", {"NB", "A7JYJ4TBSAK",         "FEEL_OFF_A_CHICKEN"}},
          {"XD", {"XD", "262GYDR741VADAMB74",  "LIKE"}},
          {"TB", {"TB", "RXWCYZ39ILATWH5B2",   "FEEL_OFF_A_CHICKEN"}},
          {"YJ", {"YJ", "9QSS2UNOW8",          "FEEL_OFF_A_CHICKEN"}},
          {"FN", {"FN", "RLMN5L3UVVVAFT42G",   "HELLO"}},
          {"AK", {"AK", "F3BLVX2M5DYPSD6N",    "IN_THE_WINTER"}},
          {"ZU", {"ZU", "R0YOPL1BCJJJH5VE3T0", "LIKE"}},
          {"AB", {"AB", "ZDWMVVOFSRWBY49A",    "LIKE"}},
          {"CY", {"CY", "5LW6OAYPUSG3LE6D61L", "IN_THE_WINTER"}},
          {"YA", {"YA", "4I47LIY0EUZ",         "LIKE"}},
          {"PV", {"PV", "ZWZFCGCLS4TD4C",      "IN_THE_WINTER"}},
          {"UT", {"UT", "E039WXQP3TU9HQ",      "SMELLS"}},
          {"VE", {"VE", "0TP7D8K60GD3H9DJBGO", "HELLO"}},
          {"CV", {"CV", "BQ28NJQ5DHQ12M23",    "SOMEONE"}},
          {"AZ", {"AZ", "JE61S0T0O93R6",       "FEEL_OFF_A_CHICKEN"}},
          {"HJ", {"HJ", "AP42QNCM7N0KC",       "SMELLS"}},
          {"MV", {"MV", "7SMM5KEQ1X",          "IN_THE_WINTER"}},
          {"LW", {"LW", "6PLJ660LFSWW9G2",     "SMELLS"}},
          {"FX", {"FX", "TP5RPLY4XEP0G58XI",   "LIKE"}},
          {"WD", {"WD", "7XAEHVJS1YRDG5I",     "FEEL_OFF_A_CHICKEN"}},
          {"WX", {"WX", "3MJME3FCSFHY",        "IN_THE_WINTER"}},
  };
  const map<string, S> mp = {
          {"YB", {"YB", "TWUMMSSIK98S",        "LIKE"}},
          {"CU", {"CU", "G0HZ7TIY5DGJ106YB",   "LIKE"}},
          {"BW", {"BW", "2MJDIKU1BI25RRTC2IS", "HOPELESS_CRACKERS"}},
          {"VI", {"VI", "QDGIZBQ25KV28C",      "IN_THE_WINTER"}},
          {"GX", {"GX", "19EOYLXIHMW5",        "SOMEONE"}},
          {"LN", {"LN", "5ZGZBC2GGL6JB",       "FEEL_OFF_A_CHICKEN"}},
          {"CA", {"CA", "A89RT9PBVB6PJN",      "HOPELESS_CRACKERS"}},
          {"ON", {"ON", "ZJATI7ZWN8CC6UROL8",  "IN_THE_WINTER"}},
          {"MS", {"MS", "S8KW3MZGM1UV",        "FEEL_OFF_A_CHICKEN"}},
          {"OH", {"OH", "YJOERGM0WI",          "LIKE"}},
          {"ZJ", {"ZJ", "1DU8FB5UJTJMOUH06TP", "IN_THE_WINTER"}},
          {"QQ", {"QQ", "080DXRCVXW63EJ2",     "HOPELESS_CRACKERS"}},
          {"ZA", {"ZA", "3RSI3R0ZX3S16I2",     "LIKE"}},
          {"UQ", {"UQ", "NQFQ0E3SW11",         "IN_THE_WINTER"}},
          {"AI", {"AI", "EBDZW94CUTGPFUZ",     "HELLO"}},
          {"VM", {"VM", "ZMEXENAO57F9IIT8",    "HELLO"}},
          {"YH", {"YH", "LDJMC9EJ5P2",         "FEEL_OFF_A_CHICKEN"}},
          {"WX", {"WX", "2UFSEZ83Y6BQI1AIW",   "HELLO"}},
          {"MZ", {"MZ", "MUQOLT5RS98IROKE",    "LIKE"}},
          {"ZF", {"ZF", "N482RYRPZEH5U4R0CEQ", "IN_THE_WINTER"}},
          {"JI", {"JI", "7BM5VP4GM97RHJ5X",    "LIKE"}},
          {"UB", {"UB", "0YPDR53GGRKU0I",      "SMELLS"}},
          {"XX", {"XX", "B7K4EQW9223",         "SMELLS"}},
          {"YA", {"YA", "YLVAZDJ4HJPN97V5",    "HOPELESS_CRACKERS"}},
          {"FK", {"FK", "KG0HD69WHK",          "FEEL_OFF_A_CHICKEN"}},
          {"MQ", {"MQ", "0W2HWO1VBTDBU23ID",   "LIKE"}},
          {"LH", {"LH", "ENZMT6X6FAPIW",       "LIKE"}},
          {"RR", {"RR", "DU4NS1TLRXO3IFGRW",   "LIKE"}},
          {"WB", {"WB", "AQ0L6EE4TI",          "SMELLS"}},
          {"XO", {"XO", "A1382HGT8ZEEYJQN",    "FEEL_OFF_A_CHICKEN"}},
          {"XJ", {"XJ", "2D90ABW8Q4PCICGF",    "SOMEONE"}},
          {"TG", {"TG", "J5SFHK6Q217CJG0",     "HOPELESS_CRACKERS"}},
          {"EX", {"EX", "Q869VVLFQFU0M",       "HOPELESS_CRACKERS"}},
          {"HT", {"HT", "EAD1R1QTLG0PVJD5",    "LIKE"}},
          {"DN", {"DN", "Y4M2TC3DCJ2NB0FM92",  "LIKE"}},
          {"LX", {"LX", "J67BRR6H34H1A0",      "LIKE"}},
          {"AN", {"AN", "QCHNB1DHLQ9T1EOG",    "HELLO"}},
          {"TZ", {"TZ", "FC4FHKY106KK1EZM",    "SOMEONE"}},
          {"TB", {"TB", "ID6KBJ1Y0R00W",       "HOPELESS_CRACKERS"}},
          {"YH", {"YH", "Q9VGO88DZGA4BIP",     "HOPELESS_CRACKERS"}},
          {"PI", {"PI", "I8UOLS13FBNCXA",      "HOPELESS_CRACKERS"}},
          {"QB", {"QB", "JW9OY2MJHD7BJPU6HJC", "HELLO"}},
          {"IW", {"IW", "VXJTNPPCW2MBQMX0",    "LIKE"}},
          {"CU", {"CU", "H1HZRGA7PSTVDJ",      "HOPELESS_CRACKERS"}},
          {"QC", {"QC", "2LGJ0K6OHK1F86IMGY",  "IN_THE_WINTER"}},
          {"FR", {"FR", "BPN87VZ54F1K",        "HOPELESS_CRACKERS"}},
          {"YP", {"YP", "ZUZ7DDG3ECDHP",       "SOMEONE"}},
          {"ND", {"ND", "SCCHQ0LYKVW34J",      "LIKE"}},
          {"LJ", {"LJ", "93NJ8AA8KLWAG8834BT", "SMELLS"}},
          {"DO", {"DO", "SXZUPYLT74T52IM4MYE", "LIKE"}},
          {"NL", {"NL", "DXAF33QQ1AXGSSZ6",    "SMELLS"}},
          {"GG", {"GG", "TX6EIQMJNX",          "SOMEONE"}},
          {"DE", {"DE", "F1T4JL7M29I",         "IN_THE_WINTER"}},
          {"SZ", {"SZ", "THBO1PN8TBLV0FZNSW9", "IN_THE_WINTER"}},
          {"AL", {"AL", "IX6F2DYLAAP2Y9ZXQ",   "FEEL_OFF_A_CHICKEN"}},
          {"ZN", {"ZN", "ZIFTA6B3XQWW",        "HOPELESS_CRACKERS"}},
          {"WQ", {"WQ", "Q78U79NB04JXKVK",     "SOMEONE"}},
          {"VW", {"VW", "LJ321PQROE8O",        "FEEL_OFF_A_CHICKEN"}},
          {"TO", {"TO", "07ZYH6BOVGSQ0BBMHIG", "LIKE"}},
          {"AW", {"AW", "VF44D4O9LSSMF5HN",    "SOMEONE"}},
          {"TB", {"TB", "H24P4I344W",          "SOMEONE"}},
          {"ZY", {"ZY", "9IQY9ERAPFOP",        "HOPELESS_CRACKERS"}},
          {"QY", {"QY", "V9JDET0XINLD2CUUYV",  "SOMEONE"}},
          {"AU", {"AU", "LPWLHPWCLGYW9RS5",    "IN_THE_WINTER"}},
          {"MQ", {"MQ", "6T9OKKO1TI0TTGHROM",  "HOPELESS_CRACKERS"}},
          {"NN", {"NN", "48E5YQE8WPSI3",       "HELLO"}},
          {"NI", {"NI", "ZJ56R71104XAF81EPAH", "IN_THE_WINTER"}},
          {"OA", {"OA", "U2HAT05IAUMHWGZ3",    "FEEL_OFF_A_CHICKEN"}},
          {"AF", {"AF", "KGNKX4DR5RL5AZ",      "IN_THE_WINTER"}},
          {"MP", {"MP", "M7JS5G299Y8X1RL8",    "HELLO"}},
          {"DW", {"DW", "VZA5VE6Y5YC7IS350G",  "FEEL_OFF_A_CHICKEN"}},
          {"NP", {"NP", "Y8S5XZWB6I6HXNXT",    "HOPELESS_CRACKERS"}},
          {"YW", {"YW", "U3VX19YXLMMOOKIK",    "FEEL_OFF_A_CHICKEN"}},
          {"RR", {"RR", "1BZUFCL71NV",         "HOPELESS_CRACKERS"}},
          {"MD", {"MD", "7KPVAAFWWU7O",        "SMELLS"}},
          {"CM", {"CM", "4GECQQCENHYU",        "IN_THE_WINTER"}},
          {"JB", {"JB", "S2FXVC1M5BZ17A",      "SMELLS"}},
          {"NY", {"NY", "Y0HBHKYYARCANW1TZ0U", "SOMEONE"}},
          {"ZI", {"ZI", "QB4U9OW32IXJ0",       "HOPELESS_CRACKERS"}},
          {"KM", {"KM", "2FKP3758AOO49OJALY",  "HOPELESS_CRACKERS"}},
          {"XP", {"XP", "B6RNNS85L29UOH",      "HOPELESS_CRACKERS"}},
          {"GX", {"GX", "2WLO809JI4BZBYOEC",   "SMELLS"}},
          {"OP", {"OP", "QDYZCGAPPDKD4TWL0Y",  "LIKE"}},
          {"BB", {"BB", "V2VORZHWCRYE7LMP",    "HELLO"}},
          {"AO", {"AO", "7FZIH6XHT3S9MQ",      "FEEL_OFF_A_CHICKEN"}},
          {"GY", {"GY", "IZ5K4GWNP8JC",        "IN_THE_WINTER"}},
          {"VY", {"VY", "V4AVU090QDYJ0F79",    "SMELLS"}},
          {"FL", {"FL", "VB7Z28LFJFIHP4J",     "SOMEONE"}},
          {"IA", {"IA", "CKUZ2TQRM779VB",      "LIKE"}},
          {"CE", {"CE", "HIUWJES5B7",          "HELLO"}},
          {"GC", {"GC", "PFQ3LNKWE07WB3QS8O",  "LIKE"}},
          {"KK", {"KK", "76KQ8H63M5",          "FEEL_OFF_A_CHICKEN"}},
          {"WA", {"WA", "BJZNCUYM5HLAOJ6U6",   "SMELLS"}},
          {"TL", {"TL", "IPU6KBCA00WQ",        "HELLO"}},
          {"HC", {"HC", "QKBJYAH0Q0XK9W",      "HELLO"}},
          {"HK", {"HK", "NMFQ56BJUJYZ4CN",     "HELLO"}},
          {"XC", {"XC", "WU4TB9QEKG9C1Y4YQW",  "SOMEONE"}},
          {"QL", {"QL", "7VZCRK61OYPPZJWCJRM", "LIKE"}},
          {"UL", {"UL", "KOIVI5BVHBTXIAXRG7",  "IN_THE_WINTER"}},
          {"GT", {"GT", "4V21YORTXLKV3Q",      "FEEL_OFF_A_CHICKEN"}},
          {"GM", {"GM", "QP3UFM1K5JZ9BYNR",    "FEEL_OFF_A_CHICKEN"}},
          {"CL", {"CL", "HU9K0VKGV8IPU",       "HOPELESS_CRACKERS"}},
          {"VY", {"VY", "3J4B4QLAHJ9XHDOGGYK", "FEEL_OFF_A_CHICKEN"}},
          {"NW", {"NW", "DUVCN5EK89O",         "HELLO"}},
          {"DN", {"DN", "X8WPJZ1H2KN",         "HELLO"}},
          {"PJ", {"PJ", "D6GEGBS7HH4",         "FEEL_OFF_A_CHICKEN"}},
          {"WX", {"WX", "VRIF43J7QAXFQWV",     "SOMEONE"}},
          {"HX", {"HX", "L6SDEWAST00LYO",      "SMELLS"}},
          {"KK", {"KK", "R1TQ8LAZX9",          "HELLO"}},
          {"GL", {"GL", "BH86WGTSIMRBAL0PBZ",  "HOPELESS_CRACKERS"}},
          {"XY", {"XY", "TFBJNGLR4NPSL33",     "HOPELESS_CRACKERS"}},
          {"GR", {"GR", "HXAKBVVMNVLXOVQ",     "IN_THE_WINTER"}},
          {"FZ", {"FZ", "2WPH37M7VQZQ63C7C4",  "LIKE"}},
          {"ZO", {"ZO", "7TZ4I7H9AFZXF9ACH",   "SMELLS"}},
          {"NV", {"NV", "A37TB97IO12",         "IN_THE_WINTER"}},
          {"XP", {"XP", "FXKI6BARPB3QE9T",     "SMELLS"}},
          {"WR", {"WR", "FW8MCLUTS8PEI7LXE6",  "FEEL_OFF_A_CHICKEN"}},
          {"YP", {"YP", "Z6H0KS1IS1822",       "SMELLS"}},
          {"SS", {"SS", "8FPSRCV9TWP3J2U",     "HOPELESS_CRACKERS"}},
          {"PT", {"PT", "QFWD3MXBF7WO7R24",    "SOMEONE"}},
          {"DH", {"DH", "7FHW2ZL7VOW",         "HOPELESS_CRACKERS"}},
          {"RZ", {"RZ", "9PFTL6WAJDJLA9N7HQ4", "IN_THE_WINTER"}},
          {"BA", {"BA", "DO8I2NEDZN9N03E4C",   "HOPELESS_CRACKERS"}},
          {"OY", {"OY", "5368VJP7CE4OGGX3D",   "FEEL_OFF_A_CHICKEN"}},
          {"HF", {"HF", "MVRFZ3MVUTHZOW",      "HOPELESS_CRACKERS"}},
          {"FW", {"FW", "OZ6FBPXYGASA",        "FEEL_OFF_A_CHICKEN"}},
          {"LG", {"LG", "PGL5UF021VH9PPKQZA",  "HELLO"}},
          {"CM", {"CM", "RUL8OTJH6103OIKGKH",  "SMELLS"}},
          {"BN", {"BN", "0GCVB45TWI6UJ",       "LIKE"}},
          {"OC", {"OC", "GDO8O7UGQJO",         "SOMEONE"}},
          {"TG", {"TG", "LKK2J89NA201CQJD",    "HOPELESS_CRACKERS"}},
          {"NT", {"NT", "U8L5U5Q9PZMRI73KO",   "FEEL_OFF_A_CHICKEN"}},
          {"WQ", {"WQ", "PH2MZ3CKGSB03KG4M8",  "IN_THE_WINTER"}},
          {"TJ", {"TJ", "KSS51VUPSPMN",        "SOMEONE"}},
          {"ST", {"ST", "5IY9Y3C06ZCOY7",      "HELLO"}},
          {"VK", {"VK", "F9OVU74QHIWR1VAEC6N", "HOPELESS_CRACKERS"}},
          {"WV", {"WV", "6TC9A3DADUIWF5XN5",   "IN_THE_WINTER"}},
          {"CU", {"CU", "EPYXH6O91CHOS31",     "SMELLS"}},
          {"CT", {"CT", "MU7H6L1M3K32F999M71", "SMELLS"}},
          {"MF", {"MF", "2Q9N4FKTHIW5GX3",     "SOMEONE"}},
          {"RA", {"RA", "E0VGIBFYSYCOZ36QLUG", "SMELLS"}},
          {"PJ", {"PJ", "2WFPCRPP0WF4",        "FEEL_OFF_A_CHICKEN"}},
          {"FT", {"FT", "ST2FTJ6JMF6KCS4X13",  "FEEL_OFF_A_CHICKEN"}},
          {"RF", {"RF", "W3RI6VBQ8RXF",        "SOMEONE"}},
          {"KZ", {"KZ", "AKPAB40YHJ65I6",      "IN_THE_WINTER"}},
          {"FQ", {"FQ", "Z6M9IW0DM7SBNVD9",    "IN_THE_WINTER"}},
          {"SJ", {"SJ", "Z2WSU1L8KQ0QFI",      "SMELLS"}},
          {"CK", {"CK", "PUNCNZRIXE29",        "SMELLS"}},
          {"UC", {"UC", "CKH988MZ3IWX",        "SMELLS"}},
          {"EC", {"EC", "P09Y5UFO0H",          "LIKE"}},
          {"ET", {"ET", "NH7O72SPB1HF",        "HELLO"}},
          {"JC", {"JC", "9U7WEHPFPPA9",        "HOPELESS_CRACKERS"}},
          {"JM", {"JM", "VSILHOQUIJW1HS0P95",  "LIKE"}},
          {"XD", {"XD", "1ANVL7B7IX6TGLO7",    "HOPELESS_CRACKERS"}},
          {"ZE", {"ZE", "IF9NAS18LB1",         "FEEL_OFF_A_CHICKEN"}},
          {"PD", {"PD", "UP3Q9IZPJGIP4OS",     "IN_THE_WINTER"}},
          {"EL", {"EL", "QNMFJSX3Z3Y720H5O",   "SMELLS"}},
          {"JE", {"JE", "NS47OK21ZV",          "LIKE"}},
          {"VO", {"VO", "D4EDQ7X4ED3EVQ9HR5",  "IN_THE_WINTER"}},
          {"JZ", {"JZ", "YDMQR24B1XGIO8R",     "SMELLS"}},
          {"KL", {"KL", "LJJ48C79I2D",         "SMELLS"}},
          {"SR", {"SR", "OQE18CPT8BD2HNN1O",   "HELLO"}},
          {"NK", {"NK", "T9TVRUSVROTV",        "LIKE"}},
          {"ZW", {"ZW", "BVWASIHIT5",          "LIKE"}},
          {"XW", {"XW", "VBIUSKIVC4O",         "HOPELESS_CRACKERS"}},
          {"NS", {"NS", "CV5GT6H917ZQ5",       "FEEL_OFF_A_CHICKEN"}},
          {"LW", {"LW", "P1E5J06CG1ED94LS21",  "SMELLS"}},
          {"AL", {"AL", "URS12EB7UDR7A",       "HOPELESS_CRACKERS"}},
          {"QE", {"QE", "BCU2B7IKJRW1TKPEE2",  "SMELLS"}},
          {"QU", {"QU", "ZFKFL58F19",          "HOPELESS_CRACKERS"}},
          {"FM", {"FM", "PKU88B0SR97NWM9SE",   "SMELLS"}},
          {"CU", {"CU", "OSL70SNRCNA",         "HOPELESS_CRACKERS"}},
          {"EO", {"EO", "2ZZ94JOSKN7WP7",      "LIKE"}},
          {"NV", {"NV", "QT4EZ76M7E0",         "FEEL_OFF_A_CHICKEN"}},
          {"SU", {"SU", "G6ZGLDM4QC",          "FEEL_OFF_A_CHICKEN"}},
          {"SK", {"SK", "FOHNFES9Z87V",        "SOMEONE"}},
          {"FY", {"FY", "8TMHKPZKMKK",         "LIKE"}},
          {"NW", {"NW", "V929M5X6GHZORLOZZ8",  "FEEL_OFF_A_CHICKEN"}},
          {"PQ", {"PQ", "4M4H80CTFNCSDDSS",    "SOMEONE"}},
          {"NB", {"NB", "A7JYJ4TBSAK",         "FEEL_OFF_A_CHICKEN"}},
          {"XD", {"XD", "262GYDR741VADAMB74",  "LIKE"}},
          {"TB", {"TB", "RXWCYZ39ILATWH5B2",   "FEEL_OFF_A_CHICKEN"}},
          {"YJ", {"YJ", "9QSS2UNOW8",          "FEEL_OFF_A_CHICKEN"}},
          {"FN", {"FN", "RLMN5L3UVVVAFT42G",   "HELLO"}},
          {"AK", {"AK", "F3BLVX2M5DYPSD6N",    "IN_THE_WINTER"}},
          {"ZU", {"ZU", "R0YOPL1BCJJJH5VE3T0", "LIKE"}},
          {"AB", {"AB", "ZDWMVVOFSRWBY49A",    "LIKE"}},
          {"CY", {"CY", "5LW6OAYPUSG3LE6D61L", "IN_THE_WINTER"}},
          {"YA", {"YA", "4I47LIY0EUZ",         "LIKE"}},
          {"PV", {"PV", "ZWZFCGCLS4TD4C",      "IN_THE_WINTER"}},
          {"UT", {"UT", "E039WXQP3TU9HQ",      "SMELLS"}},
          {"VE", {"VE", "0TP7D8K60GD3H9DJBGO", "HELLO"}},
          {"CV", {"CV", "BQ28NJQ5DHQ12M23",    "SOMEONE"}},
          {"AZ", {"AZ", "JE61S0T0O93R6",       "FEEL_OFF_A_CHICKEN"}},
          {"HJ", {"HJ", "AP42QNCM7N0KC",       "SMELLS"}},
          {"MV", {"MV", "7SMM5KEQ1X",          "IN_THE_WINTER"}},
          {"LW", {"LW", "6PLJ660LFSWW9G2",     "SMELLS"}},
          {"FX", {"FX", "TP5RPLY4XEP0G58XI",   "LIKE"}},
          {"WD", {"WD", "7XAEHVJS1YRDG5I",     "FEEL_OFF_A_CHICKEN"}},
          {"WX", {"WX", "3MJME3FCSFHY",        "IN_THE_WINTER"}},
  };
}